### ISSUE TITLE
Duplicate information of node label

### ISSUE THREAD

**Issue by nobrakal** [patrickdoc/fgl-ng#12]
Hi,

It disturbed me since I read the code: the current implementation of graph is:
```Haskell
type GraphRep a b = HM.HashMap b (Context' a b)

data Context' a b = Context'
    { heads :: !(HS.HashSet (Head a b)) -- ^ Predecessors of the node
    , self  :: !b                       -- ^ The node label
    , tails :: !(HS.HashSet (Tail a b)) -- ^ Successors of the node
} deriving (Eq, Generic, Show)
```
So the node label is stored two times: one as a key in the HashMap, one in the `Context'`.

Is this really needed ? I tried to remove the `self` record of `Context'` and successfully (it build and the semantic only changed for some functions, I certainly made mistakes) did it (only for the `Data.HashGraph.Strict` module), you can see the results here: https://github.com/nobrakal/hash-graph/commit/82a676c35ecffde422c2797216311c0f6db7e064

I don't do anything with algorithm implementation, but it can be certainly removed.

I know the definition of `Context` in the fgl paper include the node, but I think the real context can be viewed as the association `key -> value` in the HashMap.

What do you think ?

**Comment by patrickdoc** [comment]
My only worry is ending up in a position where you have a `Context` but not the node itself. `matchAny` was going to be my example, but I see that you handled that case. It is probably possible to enforce that if the user has a context they also have the node label, but I haven't given much thought to it.
(Also, it is a minor issue but `ctx & g` becomes `l & ctx g` which is not quite as nice looking.)

So, short answer: I'm open to removing it if I can be reasonably certain the user won't get into a bad position. And I'm already mostly convinced.

Long answer:

In truth, `heads` and `tails` are also duplicated and somewhat unnecessary. Storing both ends of a directed edge doubles the space complexity, but makes reversal effectively `O(1)` with a `newtype` wrapper. There are definitely cases where you want this, but also some where you don't. At the moment, the user is forced to accept my trade-offs, which I don't think is a great situation.

On the [denot](https://github.com/patrickdoc/hash-graph/tree/denot/Data/AbstractGraph) branch I am trying something a little different. People use graphs in very different ways, so I am looking to make a more general graph representation. I've been modelling graphs as a function `node -> node -> edge`, which seems to be working reasonably well so far. It is interesting to note how similar this is to `(node,node) -> edge` (adjacency matrix) or `node -> (node -> edge)` (~adjacency list).

I think the hashing-based representation is a pretty good general-use graph, so I do want to port it over. But I also want to give the user some ability to make their own. For example, if their keys are `Int`'s, they should be able to use [Data.IntMap](http://hackage.haskell.org/package/containers-0.5.11.0/docs/Data-IntMap-Lazy.html) or the strict variant directly. Another interesting solution would be to make `Context'` the node type of the graph, and then just hash it using the `self` label.

Sorry for the long post, I've just been trying to nail down a solid general core graph definition and keep finding new ways people want to use graphs.

**Comment by nobrakal** [comment]
I don't know how an user can have a `Context'` without a node, because the only way to obtain is a `Context'` is the HashMap, and thus through node. A `Context'` alone has not many sense anyway...

> `ctx & g` becomes `l & ctx g` which is not quite as nice looking
Yep, must think a bout a clean syntax `(&)`...

Short response:
I think trying this with algorithm implementation will certainly reveal if this was a good idea ^^

Long response:

* About the choices made for the implementation: I think the hashing-based is a great point of view, and efficient, view for a `fgl` implementation. Definitely need specialized modules with  `Data.IntMap`, between I am not sure on how to do that without duplicate too many code ^^.
Using a hash of the `self` may be a good idea, but it feels like a duplication, since the label can be the key itself.

* About the `denot` branch: I didn't saw that, that is a pretty way of thinking about graphs :D

**Comment by nobrakal** [comment]
Here is a version with fully removed `self` record: https://github.com/nobrakal/hash-graph/commit/46933c66ba3570fcdc06927fa06b1666d6710222
I used almost systematically the type `(b,Context' a b)`, it may be a good idea to pose `type Context a b = (b, Context' a b)`.

Tests are passing :)

**Comment by patrickdoc** [comment]
Looks good! You can go ahead and define `type Context a b = (b, Context' a b)` and make a PR. Thanks!
